---
# tasks file for samba
- name: Execute following with sudo
  become: true
  block:
    - name: Install samba
      ansible.builtin.dnf:
        name: samba
      notify:
        - Enabled and start samba
        - Permit traffic for samba service

    - name: Create directory for samba sharing
      ansible.builtin.file:
        path: "{{ samba_dir }}"
        state: directory
        mode: '0750'

    - name: Allow samba to modify files in {{ samba_dir }}
      community.general.sefcontext:
        target: "{{ samba_dir }}(/.*)?"
        setype: samba_share_t

    - name: Apply new SeLinux file contenxt to filesystem
      ansible.builtin.command: "restorecon -irv {{ samba_dir }}"
      changed_when: false
      failed_when: false
      register: _samba_out

- name: Check output
  ansible.builtin.debug:
    var: _samba_out

- name: Samba role message
  ansible.builtin.debug:
    msg: |-
      Setup completed.  Please use the following link to configure:
      https://docs.fedoraproject.org/en-US/quick-docs/samba/
