---
- name: Execute roles on server
  hosts: server
  vars_prompt:
    - name: ansible_become_pass
      prompt: "BECOME password"

  roles:
    - role: ansi_colle.server.config
      tags: config
    - role: ansi_colle.server.rclone
      tags: rclone
    - role: ansi_colle.server.dnf_automatic
      tags: dnf_automatic
    - role: ansi_colle.server.podman
      tags: podman
    - role: ansi_colle.server.onlyoffice
      tags: onlyoffice
    - role: ansi_colle.server.ansible
      tags: ansible
    - role: ansi_colle.server.dev
      tags: dev
    - role: ansi_colle.server.jenkins
      tags: jenkins
    - role: ansi_colle.linux.powershell
      tags: powershell
    - role: ansi_colle.server.cloudflared
      tags: cloudflared
    - role: ansi_colle.server.kind
      tags: kind
    - role: ansi_colle.server.samba
      tags: samba
